    <div class="footer">
        <div class="ed-container footer-content">
            <div class="ed-item m-40 main-center">
                <h2>SideFlip</h2>
            </div>
            <div class="ed-item m-30">
                <p class="main-center">Lleva tu Academia a otro nivel</p>
                <div class="main-center">
                    <span class="fa fa-facebook-square"></span>
                    <span class="fa fa-twitter-square"></span>
                    <span class="fa fa-youtube-square"></span>
                </div>
            </div>
            <div class="ed-item m-30 main-center">
            <p>2018 Copyright | Todos los derechos reservados</p>
            </div>
        </div>
        <br>
    </div>
</body>
</html>