<footer class="page-footer center-align">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                 <h2>SideFlip</h2>
              </div>
              <div class="col l4 offset-l2 s12">
                <p>Lleva tu Academia a otro nivel</p>
                <span class="fa fa-facebook-square"></span>
                <span class="fa fa-twitter-square"></span>
                <span class="fa fa-youtube-square"></span>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2018 Copyright
            | Todos los derechos reservados
            </div>
          </div>
</footer>
</body>
</html>